### ISSUE TITLE
local volume for redis in docker-compose

### ISSUE THREAD

**Issue by cnstntn-kndrtv** [ModelChimp/modelchimp#3]
Is there any way to mount local volume for Redis data in docker-compose?
i have already tried this:
```yaml
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/pgdata

```
and this:
```yaml
services:
  db:
    image: postgres
     ...
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
```

and always get same error:
```
web_1     | django.db.utils.OperationalError: could not connect to server: Connection refused
web_1     | 	Is the server running on host "db" (172.25.0.3) and accepting
web_1     | 	TCP/IP connections on port 5432?
```

if i not specify path on host machine - it works. Like this:
```yaml
services:
  db:
    image: postgres
     ...
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
```
But its not useful - Docker creates volumes somewhere in `/var/lib/docker/volumes/modelchimp_postgres-data/_data` (on Mac). It would be better to store all data in project folder.
